<?php

/**
 * BasesfGuardGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                                           $id                                                 Type: integer(4), primary key
 * @property string                                        $name                                               Type: string(255), unique
 * @property string                                        $description                                        Type: string(1000)
 * @property string                                        $created_at                                         Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string                                        $updated_at                                         Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property Doctrine_Collection|sfGuardUser[]             $users                                              
 * @property Doctrine_Collection|sfGuardPermission[]       $permissions                                        
 * @property Doctrine_Collection|sfGuardGroupPermission[]  $sfGuardGroupPermission                             
 * @property Doctrine_Collection|sfGuardUserGroup[]        $sfGuardUserGroup                                   
 *  
 * @method int                                             getId()                                             Type: integer(4), primary key
 * @method string                                          getName()                                           Type: string(255), unique
 * @method string                                          getDescription()                                    Type: string(1000)
 * @method string                                          getCreatedAt()                                      Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string                                          getUpdatedAt()                                      Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method Doctrine_Collection|sfGuardUser[]               getUsers()                                          
 * @method Doctrine_Collection|sfGuardPermission[]         getPermissions()                                    
 * @method Doctrine_Collection|sfGuardGroupPermission[]    getSfGuardGroupPermission()                         
 * @method Doctrine_Collection|sfGuardUserGroup[]          getSfGuardUserGroup()                               
 *  
 * @method sfGuardGroup                                    setId(int $val)                                     Type: integer(4), primary key
 * @method sfGuardGroup                                    setName(string $val)                                Type: string(255), unique
 * @method sfGuardGroup                                    setDescription(string $val)                         Type: string(1000)
 * @method sfGuardGroup                                    setCreatedAt(string $val)                           Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method sfGuardGroup                                    setUpdatedAt(string $val)                           Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method sfGuardGroup                                    setUsers(Doctrine_Collection $val)                  
 * @method sfGuardGroup                                    setPermissions(Doctrine_Collection $val)            
 * @method sfGuardGroup                                    setSfGuardGroupPermission(Doctrine_Collection $val) 
 * @method sfGuardGroup                                    setSfGuardUserGroup(Doctrine_Collection $val)       
 *  
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_group');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser as users', array(
             'refClass' => 'sfGuardUserGroup',
             'local' => 'group_id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardPermission as permissions', array(
             'refClass' => 'sfGuardGroupPermission',
             'local' => 'group_id',
             'foreign' => 'permission_id'));

        $this->hasMany('sfGuardGroupPermission', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardUserGroup', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}