<?php

/**
 * BasesfGuardUserPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                    $user_id                                     Type: integer(4), primary key
 * @property int                    $permission_id                               Type: integer(4), primary key
 * @property string                 $created_at                                  Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string                 $updated_at                                  Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property sfGuardUser            $sfGuardUser                                 
 * @property sfGuardPermission      $sfGuardPermission                           
 *  
 * @method int                      getUserId()                                  Type: integer(4), primary key
 * @method int                      getPermissionId()                            Type: integer(4), primary key
 * @method string                   getCreatedAt()                               Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string                   getUpdatedAt()                               Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method sfGuardUser              getSfGuardUser()                             
 * @method sfGuardPermission        getSfGuardPermission()                       
 *  
 * @method sfGuardUserPermission    setUserId(int $val)                          Type: integer(4), primary key
 * @method sfGuardUserPermission    setPermissionId(int $val)                    Type: integer(4), primary key
 * @method sfGuardUserPermission    setCreatedAt(string $val)                    Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method sfGuardUserPermission    setUpdatedAt(string $val)                    Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method sfGuardUserPermission    setSfGuardUser(sfGuardUser $val)             
 * @method sfGuardUserPermission    setSfGuardPermission(sfGuardPermission $val) 
 *  
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_permission');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('permission_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardPermission', array(
             'local' => 'permission_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}