<?php

/**
 * BasesfGuardGroupPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                     $group_id                                    Type: integer(4), primary key
 * @property int                     $permission_id                               Type: integer(4), primary key
 * @property string                  $created_at                                  Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string                  $updated_at                                  Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property sfGuardGroup            $sfGuardGroup                                
 * @property sfGuardPermission       $sfGuardPermission                           
 *  
 * @method int                       getGroupId()                                 Type: integer(4), primary key
 * @method int                       getPermissionId()                            Type: integer(4), primary key
 * @method string                    getCreatedAt()                               Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string                    getUpdatedAt()                               Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method sfGuardGroup              getSfGuardGroup()                            
 * @method sfGuardPermission         getSfGuardPermission()                       
 *  
 * @method sfGuardGroupPermission    setGroupId(int $val)                         Type: integer(4), primary key
 * @method sfGuardGroupPermission    setPermissionId(int $val)                    Type: integer(4), primary key
 * @method sfGuardGroupPermission    setCreatedAt(string $val)                    Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method sfGuardGroupPermission    setUpdatedAt(string $val)                    Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method sfGuardGroupPermission    setSfGuardGroup(sfGuardGroup $val)           
 * @method sfGuardGroupPermission    setSfGuardPermission(sfGuardPermission $val) 
 *  
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardGroupPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_group_permission');
        $this->hasColumn('group_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('permission_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardGroup', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardPermission', array(
             'local' => 'permission_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}