<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                 $user_id                         Type: integer(4)
 * @property string              $first_name                      Type: string(30)
 * @property string              $last_name                       Type: string(30)
 * @property string              $facebook_uid                    Type: string(20)
 * @property string              $email                           Type: string(255)
 * @property string              $email_hash                      Type: string(255)
 * @property sfGuardUser         $sfGuardUser                     
 *  
 * @method int                   getUserId()                      Type: integer(4)
 * @method string                getFirstName()                   Type: string(30)
 * @method string                getLastName()                    Type: string(30)
 * @method string                getFacebookUid()                 Type: string(20)
 * @method string                getEmail()                       Type: string(255)
 * @method string                getEmailHash()                   Type: string(255)
 * @method sfGuardUser           getSfGuardUser()                 
 *  
 * @method sfGuardUserProfile    setUserId(int $val)              Type: integer(4)
 * @method sfGuardUserProfile    setFirstName(string $val)        Type: string(30)
 * @method sfGuardUserProfile    setLastName(string $val)         Type: string(30)
 * @method sfGuardUserProfile    setFacebookUid(string $val)      Type: string(20)
 * @method sfGuardUserProfile    setEmail(string $val)            Type: string(255)
 * @method sfGuardUserProfile    setEmailHash(string $val)        Type: string(255)
 * @method sfGuardUserProfile    setSfGuardUser(sfGuardUser $val) 
 *  
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('first_name', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('last_name', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('facebook_uid', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email_hash', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->index('facebook_uid_index', array(
             'fields' => 
             array(
              0 => 'facebook_uid',
             ),
             'unique' => true,
             ));
        $this->index('email_index', array(
             'fields' => 
             array(
              0 => 'email',
             ),
             'unique' => true,
             ));
        $this->index('email_hash_index', array(
             'fields' => 
             array(
              0 => 'email_hash',
             ),
             'unique' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}