<?php

/**
 * BasesfGuardRememberKey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                 $id                              Type: integer(4), primary key
 * @property int                 $user_id                         Type: integer(4)
 * @property string              $remember_key                    Type: string(32)
 * @property string              $ip_address                      Type: string(50), primary key
 * @property string              $created_at                      Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string              $updated_at                      Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property sfGuardUser         $sfGuardUser                     
 *  
 * @method int                   getId()                          Type: integer(4), primary key
 * @method int                   getUserId()                      Type: integer(4)
 * @method string                getRememberKey()                 Type: string(32)
 * @method string                getIpAddress()                   Type: string(50), primary key
 * @method string                getCreatedAt()                   Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string                getUpdatedAt()                   Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method sfGuardUser           getSfGuardUser()                 
 *  
 * @method sfGuardRememberKey    setId(int $val)                  Type: integer(4), primary key
 * @method sfGuardRememberKey    setUserId(int $val)              Type: integer(4)
 * @method sfGuardRememberKey    setRememberKey(string $val)      Type: string(32)
 * @method sfGuardRememberKey    setIpAddress(string $val)        Type: string(50), primary key
 * @method sfGuardRememberKey    setCreatedAt(string $val)        Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method sfGuardRememberKey    setUpdatedAt(string $val)        Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method sfGuardRememberKey    setSfGuardUser(sfGuardUser $val) 
 *  
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardRememberKey extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_remember_key');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('remember_key', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('ip_address', 'string', 50, array(
             'type' => 'string',
             'primary' => true,
             'length' => 50,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}