<?php

/**
 * BasesfGuardUserGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int               $user_id                           Type: integer(4), primary key
 * @property int               $group_id                          Type: integer(4), primary key
 * @property string            $created_at                        Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string            $updated_at                        Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property sfGuardUser       $sfGuardUser                       
 * @property sfGuardGroup      $sfGuardGroup                      
 *  
 * @method int                 getUserId()                        Type: integer(4), primary key
 * @method int                 getGroupId()                       Type: integer(4), primary key
 * @method string              getCreatedAt()                     Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string              getUpdatedAt()                     Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method sfGuardUser         getSfGuardUser()                   
 * @method sfGuardGroup        getSfGuardGroup()                  
 *  
 * @method sfGuardUserGroup    setUserId(int $val)                Type: integer(4), primary key
 * @method sfGuardUserGroup    setGroupId(int $val)               Type: integer(4), primary key
 * @method sfGuardUserGroup    setCreatedAt(string $val)          Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method sfGuardUserGroup    setUpdatedAt(string $val)          Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method sfGuardUserGroup    setSfGuardUser(sfGuardUser $val)   
 * @method sfGuardUserGroup    setSfGuardGroup(sfGuardGroup $val) 
 *  
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_group');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('group_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardGroup', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}