<?php

/**
 * BasesfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                                          $id                                                Type: integer(4), primary key
 * @property string                                       $username                                          Type: string(128), unique
 * @property string                                       $algorithm                                         Type: string(128), default "sha1"
 * @property string                                       $salt                                              Type: string(128)
 * @property string                                       $password                                          Type: string(128)
 * @property bool                                         $is_active                                         Type: boolean, default "1"
 * @property bool                                         $is_super_admin                                    Type: boolean
 * @property string                                       $last_login                                        Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string                                       $created_at                                        Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string                                       $updated_at                                        Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property Doctrine_Collection|sfGuardGroup[]           $groups                                            
 * @property Doctrine_Collection|sfGuardPermission[]      $permissions                                       
 * @property Doctrine_Collection|sfGuardUserPermission[]  $sfGuardUserPermission                             
 * @property Doctrine_Collection|sfGuardUserGroup[]       $sfGuardUserGroup                                  
 * @property sfGuardRememberKey                           $RememberKeys                                      
 * @property sfGuardUserProfile                           $Profile                                           
 * @property Doctrine_Collection|Post[]                   $Post                                              
 * @property UserProfile                                  $UserProfile                                       
 *  
 * @method int                                            getId()                                            Type: integer(4), primary key
 * @method string                                         getUsername()                                      Type: string(128), unique
 * @method string                                         getAlgorithm()                                     Type: string(128), default "sha1"
 * @method string                                         getSalt()                                          Type: string(128)
 * @method string                                         getPassword()                                      Type: string(128)
 * @method bool                                           getIsActive()                                      Type: boolean, default "1"
 * @method bool                                           getIsSuperAdmin()                                  Type: boolean
 * @method string                                         getLastLogin()                                     Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string                                         getCreatedAt()                                     Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string                                         getUpdatedAt()                                     Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method Doctrine_Collection|sfGuardGroup[]             getGroups()                                        
 * @method Doctrine_Collection|sfGuardPermission[]        getPermissions()                                   
 * @method Doctrine_Collection|sfGuardUserPermission[]    getSfGuardUserPermission()                         
 * @method Doctrine_Collection|sfGuardUserGroup[]         getSfGuardUserGroup()                              
 * @method sfGuardRememberKey                             getRememberKeys()                                  
 * @method sfGuardUserProfile                             getProfile()                                       
 * @method Doctrine_Collection|Post[]                     getPost()                                          
 * @method UserProfile                                    getUserProfile()                                   
 *  
 * @method sfGuardUser                                    setId(int $val)                                    Type: integer(4), primary key
 * @method sfGuardUser                                    setUsername(string $val)                           Type: string(128), unique
 * @method sfGuardUser                                    setAlgorithm(string $val)                          Type: string(128), default "sha1"
 * @method sfGuardUser                                    setSalt(string $val)                               Type: string(128)
 * @method sfGuardUser                                    setPassword(string $val)                           Type: string(128)
 * @method sfGuardUser                                    setIsActive(bool $val)                             Type: boolean, default "1"
 * @method sfGuardUser                                    setIsSuperAdmin(bool $val)                         Type: boolean
 * @method sfGuardUser                                    setLastLogin(string $val)                          Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method sfGuardUser                                    setCreatedAt(string $val)                          Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method sfGuardUser                                    setUpdatedAt(string $val)                          Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method sfGuardUser                                    setGroups(Doctrine_Collection $val)                
 * @method sfGuardUser                                    setPermissions(Doctrine_Collection $val)           
 * @method sfGuardUser                                    setSfGuardUserPermission(Doctrine_Collection $val) 
 * @method sfGuardUser                                    setSfGuardUserGroup(Doctrine_Collection $val)      
 * @method sfGuardUser                                    setRememberKeys(sfGuardRememberKey $val)           
 * @method sfGuardUser                                    setProfile(sfGuardUserProfile $val)                
 * @method sfGuardUser                                    setPost(Doctrine_Collection $val)                  
 * @method sfGuardUser                                    setUserProfile(UserProfile $val)                   
 *  
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('username', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 128,
             ));
        $this->hasColumn('algorithm', 'string', 128, array(
             'type' => 'string',
             'default' => 'sha1',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('salt', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('password', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_super_admin', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('last_login', 'timestamp', null, array(
             'type' => 'timestamp',
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardGroup as groups', array(
             'refClass' => 'sfGuardUserGroup',
             'local' => 'user_id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardPermission as permissions', array(
             'refClass' => 'sfGuardUserPermission',
             'local' => 'user_id',
             'foreign' => 'permission_id'));

        $this->hasMany('sfGuardUserPermission', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUserGroup', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardRememberKey as RememberKeys', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardUserProfile as Profile', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Post', array(
             'local' => 'id',
             'foreign' => 'contributor_id'));

        $this->hasOne('UserProfile', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}