<?php

use Symfony\Component\Process\Process;

/**
 * Post
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    musique-approximative
 * @subpackage model
 * @author     Tristan Rivoallan <tristan@rivoallan.net>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Post extends BasePost
{
  public function getContributorDisplayName()
  {
    return $this->getSfGuardUser()->getDisplayName();
  }

  /**
   * Construit l'URL canonique d'un fichier audio.
   *
   * Seul le nom de fichier est encode, et avec rawurlencode : dans un segment
   * de chemin, urlencode() produirait un « + » la ou il faut « %20 ».
   *
   * @param string      $filename Nom du fichier dans web/tracks/
   * @param string|null $scheme   'http' ou 'https' pour forcer une URL absolue.
   *                              Null conserve app_urls_tracks tel quel.
   *
   *                              Si app_urls_tracks n'a pas de schema du tout
   *                              (base relative au protocole, ex: "//cdn...",
   *                              ou base totalement relative, ex: "/tracks"
   *                              ou ""), $scheme est utilise pour produire une
   *                              URL absolue.
   *
   *                              Si app_urls_tracks a deja son propre schema
   *                              (ex: "http://cdn..."), $scheme est ignore :
   *                              reecrire le schema d'une URL deja absolue et
   *                              explicitement configuree serait surprenant.
   * @return string
   */
  public static function buildTrackUrl($filename, $scheme = null)
  {
    $base = rtrim(sfConfig::get('app_urls_tracks'), '/');

    if (null !== $scheme) {
      if (0 === strpos($base, '//')) {
        // Base relative au protocole : on prefixe le schema demande.
        $base = $scheme.':'.$base;
      } elseif (!preg_match('#^[a-z][a-z0-9+.-]*://#i', $base)) {
        // Base sans aucun schema (chemin relatif, eventuellement vide) :
        // on la rend absolue sous le schema demande.
        $base = $scheme.'://'.$base;
      }
      // Sinon, la base est deja absolue avec son propre schema : no-op
      // volontaire, voir docblock ci-dessus.
    }

    return sprintf('%s/%s', $base, rawurlencode($filename));
  }

  /**
   * @param string|null $scheme voir self::buildTrackUrl()
   * @return string
   */
  public function getTrackUrl($scheme = null)
  {
    return self::buildTrackUrl($this->track_filename, $scheme);
  }

  /**
   * @see http://jsonapi.org/format/#url-based-json-api
   */
  public function toJson(sfWebRequest $request, sfContext $context, $postPrevious = null, $postNext = null)
  {
    // Get post as array
    $post = parent::toArray(true, false);

    // Post ID
    $post['id'] = $post['slug'];

    // Post canonical URL
    $post['href'] = $context->getRouting()->generate(
      'post_show', array(
        'slug'   => $post['id'],
        'format' => 'json'
      ),
      true
    );
    // Post canonical URL
    unset($post['slug']);

    // Body
    $context->getConfiguration()->loadHelpers(['Markdown']);
    $bodyMarkdown = $post['body'];
    $bodyHtml = Markdown($bodyMarkdown);
    unset($post['body']);
    $post['body'] = array('html' => $bodyHtml, 'markdown' => $bodyMarkdown);

    // Track
    $post['track'] = array(
      'href'   => $this->getTrackUrl($request->isSecure() ? 'https' : 'http'),
      'title'  => $post['track_title'],
      'author' => $post['track_author'],
      'md5'    => $post['track_md5']
    );
    unset(
      $post['track_filename'],
      $post['track_title'],
      $post['track_author'],
      $post['track_md5']
    );

    // Contributor
    $post['contributor'] = array(
      'name'         => $this->getContributorDisplayName(),
      'slug'         => $this->getSfGuardUser()->username,
      'href_website' => $this->getSfGuardUser()->UserProfile->website_url
    );
    unset(
      $post['contributor_id'],
      $post['contributor_name'],
      $post['contributor_slug']
    );

    // Hidden fields
    unset(
      $post['sfGuardUser'],
      $post['svn_revision'],
      $post['is_online']
    );


    // Post links
    $post['links'] = array();

    // Previous post
    if ($postPrevious) {
      $post['links']['post_previous'] = $context->getRouting()->generate(
        'post_show', array(
          'slug'   => $postPrevious->slug,
          'format' => 'json'
        ),
        true
      );
    }

    // Next post
    if ($postNext) {
      $post['links']['post_next'] = $context->getRouting()->generate(
        'post_show', array(
          'slug'   => $postNext->slug,
          'format' => 'json'
        ),
        true
      );
    }

    // Contributor playlist
    $post['links']['contributor_playlist'] = $context->getRouting()->generate(
      'post_list',
      array(
        'c' => $post['contributor']['slug'],
        'format' => 'json'
      ),
      true
    );

    // Avatar
    $post['links']['avatar'] = sprintf('%s/avatars/%s.png', $request->getUriPrefix(), $post['id']);

    // Encode data to JSON
    return json_encode($post);
  }

  /**
   * Actions performed after post has been successfully saved to database.
   * - Delete frontend template cache
   * - Generate track picture
   */
  public function postSave($event)
  {
    // Frontend template cache directory
    $frontendCacheDir = sprintf(
      '%s/frontend/%s/template',
      sfConfig::get('sf_cache_dir'),
      sfConfig::get('sf_environment')
    );

    // Generate track picture from logo
    $webDir = sfConfig::get('sf_web_dir');
    $postId = $event->getInvoker()->id;
    if (!file_exists(sprintf('%s/avatars/%s.png'), $webDir, $postId)) {
      $process = new Process(
        sprintf(
          'bndrimg %s/images/logo_500.png --output=%s/avatars/%s.png --seed=%s',
          $webDir,
          $webDir,
          $postId,
          $postId
        )
      );
      $process->setTimeout(10);
      // $process->run();

      // 10% chance to get a colored avatar
      if (in_array(random_int(0, 9), range(0, 9))) {
        $process = new Process(
          sprintf(
            'convert -type Grayscale %s/avatars/%s.png %s/avatars/%s.png',
            $webDir,
            $postId,
            $webDir,
            $postId
          )
        );
        // $process->start();
      }
    }

    // Delete frontend cache *asynchronously*
    // @see https://symfony.com/doc/current/components/process.html#running-processes-asynchronously
    $process = new Process(sprintf('rm -rf %s/*', $frontendCacheDir));
    $process->start();
  }
}
