<?php

use Symfony\Component\Process\Process;

/**
 * Post
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    musique-approximative
 * @subpackage model
 * @author     Tristan Rivoallan <tristan@rivoallan.net>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Post extends BasePost
{
  public function getContributorDisplayName()
  {
    return $this->getSfGuardUser()->getDisplayName();
  }

  /**
   * Construit l'URL canonique d'un fichier audio.
   *
   * Seul le nom de fichier est encode, et avec rawurlencode : dans un segment
   * de chemin, urlencode() produirait un « + » la ou il faut « %20 ».
   *
   * @param string      $filename Nom du fichier dans web/tracks/
   * @param string|null $scheme   'http' ou 'https' pour forcer une URL absolue.
   *                              Null conserve app_urls_tracks tel quel.
   *
   *                              Seule une base relative au protocole
   *                              (ex: "//cdn...") peut etre qualifiee : elle
   *                              porte deja l'autorite (l'hote), donc prefixer
   *                              le schema suffit a la rendre absolue.
   *
   *                              Si app_urls_tracks a deja son propre schema
   *                              (ex: "http://cdn..."), $scheme est ignore :
   *                              reecrire le schema d'une URL deja absolue et
   *                              explicitement configuree serait surprenant.
   *
   *                              Une base sans autorite du tout (chemin
   *                              relatif, ex: "/tracks", ou vide) n'a pas
   *                              d'hote a qualifier : $scheme ne peut pas en
   *                              faire une URL absolue (il manquerait
   *                              l'autorite), donc la base est renvoyee
   *                              inchangee. Ce n'est pas un manque : tous les
   *                              profils livres configurent
   *                              tracks: //${APP_DOMAIN}/tracks.
   * @return string
   */
  public static function buildTrackUrl($filename, $scheme = null)
  {
    $base = rtrim(sfConfig::get('app_urls_tracks'), '/');

    if (null !== $scheme && 0 === strpos($base, '//')) {
      $base = $scheme.':'.$base;
    }

    return sprintf('%s/%s', $base, rawurlencode($filename));
  }

  /**
   * @param string|null $scheme voir self::buildTrackUrl()
   * @return string
   */
  public function getTrackUrl($scheme = null)
  {
    return self::buildTrackUrl($this->track_filename, $scheme);
  }

  /**
   * @see http://jsonapi.org/format/#url-based-json-api
   */
  public function toJson(sfWebRequest $request, sfContext $context, $postPrevious = null, $postNext = null)
  {
    // Get post as array
    $post = parent::toArray(true, false);

    // Post ID
    $post['id'] = $post['slug'];

    // Post canonical URL
    $post['href'] = $context->getRouting()->generate(
      'post_show', array(
        'slug'   => $post['id'],
        'format' => 'json'
      ),
      true
    );
    // Post canonical URL
    unset($post['slug']);

    // Body
    $context->getConfiguration()->loadHelpers(['Markdown']);
    $bodyMarkdown = $post['body'];
    $bodyHtml = Markdown($bodyMarkdown);
    unset($post['body']);
    $post['body'] = array('html' => $bodyHtml, 'markdown' => $bodyMarkdown);

    // Track
    $post['track'] = array(
      'href'   => $this->getTrackUrl($request->isSecure() ? 'https' : 'http'),
      'title'  => $post['track_title'],
      'author' => $post['track_author'],
      'md5'    => $post['track_md5']
    );
    unset(
      $post['track_filename'],
      $post['track_title'],
      $post['track_author'],
      $post['track_md5']
    );

    // Contributor
    $post['contributor'] = array(
      'name'         => $this->getContributorDisplayName(),
      'slug'         => $this->getSfGuardUser()->username,
      'href_website' => $this->getSfGuardUser()->getWebsiteUrl()
    );
    unset(
      $post['contributor_id'],
      $post['contributor_name'],
      $post['contributor_slug']
    );

    // Hidden fields
    unset(
      $post['sfGuardUser'],
      $post['svn_revision'],
      $post['is_online']
    );


    // Post links
    $post['links'] = array();

    // Previous post
    if ($postPrevious) {
      $post['links']['post_previous'] = $context->getRouting()->generate(
        'post_show', array(
          'slug'   => $postPrevious->slug,
          'format' => 'json'
        ),
        true
      );
    }

    // Next post
    if ($postNext) {
      $post['links']['post_next'] = $context->getRouting()->generate(
        'post_show', array(
          'slug'   => $postNext->slug,
          'format' => 'json'
        ),
        true
      );
    }

    // Contributor playlist
    $post['links']['contributor_playlist'] = $context->getRouting()->generate(
      'post_list',
      array(
        'c' => $post['contributor']['slug'],
        'format' => 'json'
      ),
      true
    );

    // Avatar
    $post['links']['avatar'] = sprintf('%s/avatars/%s.png', $request->getUriPrefix(), $post['id']);

    // Encode data to JSON
    return json_encode($post);
  }

  /**
   * Chemin absolu du fichier audio, que le fichier existe ou non.
   *
   * Meme convention que le reste du code (executeMd5, le flux RSS) :
   * sf_web_dir . '/tracks/' . track_filename, jamais un chemin relatif a
   * __DIR__ comme le faisait l'ancienne tache rebuild-md5.
   *
   * @return string
   */
  public function getTrackPath()
  {
    return sfConfig::get('sf_web_dir').'/tracks/'.$this->track_filename;
  }

  /**
   * Renseigne track_size et track_duration a partir du fichier audio.
   *
   * - track_size vient de filesize().
   * - track_duration vient de getID3 (playtime_seconds, arrondi a la
   *   seconde) : getID3 sait lire les en-tetes Xing/VBRI et gerer le VBR,
   *   ce qu'un parseur de frames maison ferait mal.
   *
   * Ne fait rien (et renvoie false) si le fichier est illisible : sur
   * l'archive de production, une partie des fichiers references en base a
   * disparu, et ce n'est pas une erreur qui doit interrompre un traitement
   * par lots.
   *
   * Ne fait rien non plus (et renvoie false) si les deux colonnes sont deja
   * renseignees, sauf si $force vaut true : evite de rouvrir et
   * re-analyser inutilement un fichier au fil des sauvegardes repetees d'un
   * post existant.
   *
   * Si getID3 ne parvient pas a analyser le fichier comme un flux audio
   * (playtime_seconds absent), track_size est tout de meme renseigne mais
   * track_duration reste NULL : une degradation correcte, pas un echec.
   *
   * @param  bool $force Recalcule meme si track_size et track_duration
   *                      sont deja tous les deux renseignes.
   * @return bool         true si track_size et/ou track_duration ont change.
   */
  public function fillTrackMetadata($force = false)
  {
    if (!$force && null !== $this->track_size && null !== $this->track_duration) {
      return false;
    }

    $path = $this->getTrackPath();

    if (!is_readable($path)) {
      return false;
    }

    $changed = false;

    $size = filesize($path);
    if (false !== $size && $size !== $this->track_size) {
      $this->track_size = $size;
      $changed = true;
    }

    $getID3 = new getID3();
    $info = $getID3->analyze($path);

    if (isset($info['playtime_seconds'])) {
      $duration = (int) round($info['playtime_seconds']);
      if ($duration !== $this->track_duration) {
        $this->track_duration = $duration;
        $changed = true;
      }
    }

    return $changed;
  }

  /**
   * Renseigne la duree et la taille du morceau avant l'ecriture en base,
   * pour qu'un nouveau post les porte des son premier INSERT et n'exige pas
   * un second aller-retour vers la base. Un fichier qui arrive apres coup
   * (post deja cree, fichier televerse plus tard) est rattrape par la tache
   * musiqueapproximative:scan-tracks, pas ici.
   */
  public function preSave($event)
  {
    $this->fillTrackMetadata();
  }

  /**
   * Actions performed after post has been successfully saved to database.
   * - Delete frontend template cache
   * - Generate track picture
   */
  public function postSave($event)
  {
    // Frontend template cache directory
    $frontendCacheDir = sprintf(
      '%s/frontend/%s/template',
      sfConfig::get('sf_cache_dir'),
      sfConfig::get('sf_environment')
    );

    // Generate track picture from logo
    //
    // Bug preexistant corrige au passage (decouvert en verifiant la tache
    // scan-tracks : tout ->save() y compris hors de cette branche feature
    // levait une TypeError non rattrapee ici, avant meme d'atteindre la
    // purge du cache ci-dessous) :
    //  - file_exists(sprintf(...), $webDir, $postId) : la parenthese
    //    fermante de sprintf() etait mal placee, ce qui produisait
    //    toujours false (sprintf() sans arguments de substitution) et
    //    faisait donc toujours regenerer l'avatar.
    //  - new Process($commandeString) : symfony/process ^5.4 n'accepte
    //    plus une commande sous forme de chaine dans le constructeur (seul
    //    un tableau d'arguments est accepte) ; Process::fromShellCommandline()
    //    est l'equivalent officiellement supporte pour une chaine shell,
    //    sans changer le comportement (run()/start() restent tels quels).
    $webDir = sfConfig::get('sf_web_dir');
    $postId = $event->getInvoker()->id;
    if (!file_exists(sprintf('%s/avatars/%s.png', $webDir, $postId))) {
      $process = Process::fromShellCommandline(
        sprintf(
          'bndrimg %s/images/logo_500.png --output=%s/avatars/%s.png --seed=%s',
          $webDir,
          $webDir,
          $postId,
          $postId
        )
      );
      $process->setTimeout(10);
      // $process->run();

      // 10% chance to get a colored avatar
      if (in_array(random_int(0, 9), range(0, 9))) {
        $process = Process::fromShellCommandline(
          sprintf(
            'convert -type Grayscale %s/avatars/%s.png %s/avatars/%s.png',
            $webDir,
            $postId,
            $webDir,
            $postId
          )
        );
        // $process->start();
      }
    }

    // Delete frontend cache *asynchronously*
    // @see https://symfony.com/doc/current/components/process.html#running-processes-asynchronously
    $process = Process::fromShellCommandline(sprintf('rm -rf %s/*', $frontendCacheDir));
    $process->start();
  }
}
