<?php

/**
 * BasePost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int          $id                              Type: integer, primary key
 * @property string       $body                            Type: string
 * @property string       $track_title                     Type: string
 * @property string       $track_author                    Type: string
 * @property string       $track_filename                  Type: string
 * @property string       $track_md5                       Type: string(32)
 * @property int          $track_duration                  Type: integer
 * @property int          $track_size                      Type: integer
 * @property string       $buy_url                         Type: string(255)
 * @property int          $svn_revision                    Type: integer
 * @property string       $publish_on                      Type: datetime, Date and time in ISO-8601 format (YYYY-MM-DD HH:MI)
 * @property bool         $is_online                       Type: boolean
 * @property int          $contributor_id                  Type: integer(4)
 * @property string       $created_at                      Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string       $updated_at                      Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string       $slug                            Type: string(255), unique
 * @property sfGuardUser  $sfGuardUser                     
 *  
 * @method int            getId()                          Type: integer, primary key
 * @method string         getBody()                        Type: string
 * @method string         getTrackTitle()                  Type: string
 * @method string         getTrackAuthor()                 Type: string
 * @method string         getTrackFilename()               Type: string
 * @method string         getTrackMd5()                    Type: string(32)
 * @method int            getTrackDuration()               Type: integer
 * @method int            getTrackSize()                   Type: integer
 * @method string         getBuyUrl()                      Type: string(255)
 * @method int            getSvnRevision()                 Type: integer
 * @method string         getPublishOn()                   Type: datetime, Date and time in ISO-8601 format (YYYY-MM-DD HH:MI)
 * @method bool           getIsOnline()                    Type: boolean
 * @method int            getContributorId()               Type: integer(4)
 * @method string         getCreatedAt()                   Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string         getUpdatedAt()                   Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string         getSlug()                        Type: string(255), unique
 * @method sfGuardUser    getSfGuardUser()                 
 *  
 * @method Post           setId(int $val)                  Type: integer, primary key
 * @method Post           setBody(string $val)             Type: string
 * @method Post           setTrackTitle(string $val)       Type: string
 * @method Post           setTrackAuthor(string $val)      Type: string
 * @method Post           setTrackFilename(string $val)    Type: string
 * @method Post           setTrackMd5(string $val)         Type: string(32)
 * @method Post           setTrackDuration(int $val)       Type: integer
 * @method Post           setTrackSize(int $val)           Type: integer
 * @method Post           setBuyUrl(string $val)           Type: string(255)
 * @method Post           setSvnRevision(int $val)         Type: integer
 * @method Post           setPublishOn(string $val)        Type: datetime, Date and time in ISO-8601 format (YYYY-MM-DD HH:MI)
 * @method Post           setIsOnline(bool $val)           Type: boolean
 * @method Post           setContributorId(int $val)       Type: integer(4)
 * @method Post           setCreatedAt(string $val)        Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method Post           setUpdatedAt(string $val)        Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method Post           setSlug(string $val)             Type: string(255), unique
 * @method Post           setSfGuardUser(sfGuardUser $val) 
 *  
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('post');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('track_title', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('track_author', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('track_filename', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('track_md5', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('track_duration', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'Duree du morceau en secondes, nulle tant que non calculee',
             ));
        $this->hasColumn('track_size', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'Taille du fichier en octets, nulle tant que non calculee',
             ));
        $this->hasColumn('buy_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('svn_revision', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('publish_on', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));
        $this->hasColumn('is_online', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('contributor_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('online_publish_idx', array(
             'fields' => 
             array(
              0 => 'is_online',
              1 => 'publish_on',
             ),
             ));
        $this->index('track_author_idx', array(
             'fields' => 
             array(
              'track_author' => 
              array(
              'length' => 191,
              ),
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'contributor_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'track_author',
              1 => 'track_title',
             ),
             'canUpdate' => true,
             ));
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'track_author',
              1 => 'track_title',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
        $this->actAs($searchable0);
    }
}