<?php

/**
 * BaseUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int          $user_id                         Type: integer(4)
 * @property string       $display_name                    Type: string(255)
 * @property string       $email                           Type: string(255)
 * @property string       $website_url                     Type: string(255)
 * @property sfGuardUser  $sfGuardUser                     
 *  
 * @method int            getUserId()                      Type: integer(4)
 * @method string         getDisplayName()                 Type: string(255)
 * @method string         getEmail()                       Type: string(255)
 * @method string         getWebsiteUrl()                  Type: string(255)
 * @method sfGuardUser    getSfGuardUser()                 
 *  
 * @method UserProfile    setUserId(int $val)              Type: integer(4)
 * @method UserProfile    setDisplayName(string $val)      Type: string(255)
 * @method UserProfile    setEmail(string $val)            Type: string(255)
 * @method UserProfile    setWebsiteUrl(string $val)       Type: string(255)
 * @method UserProfile    setSfGuardUser(sfGuardUser $val) 
 *  
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_profile');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('display_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('website_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->index('email_index', array(
             'fields' => 
             array(
              0 => 'email',
             ),
             'unique' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}