# yaml-language-server: $schema=../schemas/recettes.schema.json

# Recettes pour divers désastres
recettes:
  amour:
    desastre: amour
    enabled: true
    scripts:
      - /frontend/assets/javascripts/animejs/anime-3.2.2.min.js
  bleu:
    desastre: bleu
    enabled: true
  danse:
    desastre: danse
    enabled: true
  fish:
    desastre: fish
    enabled: true
  light:
    desastre: light
    enabled: true
    scripts:
      - /frontend/assets/javascripts/animejs/anime-3.2.2.min.js
  musique:
    desastre: musique
    enabled: true
    scripts:
      - /frontend/assets/javascripts/animejs/anime-3.2.2.min.js
  noir:
    desastre: noir
    enabled: true
    scripts:
      - /frontend/assets/javascripts/animejs/anime-3.2.2.min.js
  robot:
    desastre: robot
    enabled: true
